In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

# --- Data ---
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3]
])
y = np.array([
    [2],
    [4],
    [5]
])

# --- Hyperparameters ---
eta = 0.1
epochs = 20
N = X.shape[0]

# --- Initialize weights ---
w = np.zeros((X.shape[1], 1))

# --- Training loop (Gradient Descent) ---
for epoch in range(epochs):
    # Forward pass
    y_pred = X @ w

    # Compute loss
    loss = (1 / (2 * N)) * np.sum((y_pred - y) ** 2)

    # Gradient
    gradient = (1 / N) * (X.T @ (y_pred - y))

    # Update weights
    w = w - eta * gradient

    print(f"Epoch {epoch+1}")
    print("Weights:\n", w)
    print("Loss:", loss)
    print()

print("Final Weights:\n", w)

# --- Error Metrics ---
mse = 2 * loss
rmse = np.sqrt(mse)
mae = np.mean(np.abs(y_pred - y))

print(f"1. Mean Squared Error (MSE): {mse:.6f}")
print(f"2. Root Mean Squared Error (RMSE): {rmse:.6f}")
print(f"3. Mean Absolute Error (MAE): {mae:.6f}")

# --- Train/Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Retrain with training data
w_new = np.zeros((X_train.shape[1], 1))
N_train = X_train.shape[0]

for epoch in range(30):
    y_pred_train = X_train @ w_new
    loss_train = (1 / (2 * N_train)) * np.sum((y_pred_train - y_train) ** 2)
    gradient_new = (1 / N_train) * (X_train.T @ (y_pred_train - y_train))
    w_new = w_new - eta * gradient_new

print("\nFinal Weights after retraining:\n", w_new)

# --- Evaluate Training Error ---
y_pred_train = X_train @ w_new
mse_train = mean_squared_error(y_train, y_pred_train)
rmse_train = np.sqrt(mse_train)
mae_train = mean_absolute_error(y_train, y_pred_train)

print(f"\nTraining Mean Squared Error (MSE): {mse_train:.6f}")
print(f"Training Root Mean Squared Error (RMSE): {rmse_train:.6f}")
print(f"Training Mean Absolute Error (MAE): {mae_train:.6f}")

# --- Evaluate Testing Error ---
y_pred_test = X_test @ w_new
mse_test = mean_squared_error(y_test, y_pred_test)
rmse_test = np.sqrt(mse_test)
mae_test = mean_absolute_error(y_test, y_pred_test)

print(f"\nTesting Mean Squared Error (MSE): {mse_test:.6f}")
print(f"Testing Root Mean Squared Error (RMSE): {rmse_test:.6f}")
print(f"Testing Mean Absolute Error (MAE): {mae_test:.6f}")

Epoch 1
Weights:
 [[0.36666667]
 [0.83333333]]
Loss: 7.5

Epoch 2
Weights:
 [[0.53      ]
 [1.20444444]]
Loss: 1.5098148148148152

Epoch 3
Weights:
 [[0.60277778]
 [1.3697037 ]]
Loss: 0.3217257201646089

Epoch 4
Weights:
 [[0.63522593]
 [1.44328642]]
Loss: 0.08608093529949704

Epoch 5
Weights:
 [[0.64971272]
 [1.47604091]]
Loss: 0.039343275576639775

Epoch 6
Weights:
 [[0.65619993]
 [1.49061261]]
Loss: 0.03007332111868083

Epoch 7
Weights:
 [[0.65912408]
 [1.49708674]]
Loss: 0.02823468552762311

Epoch 8
Weights:
 [[0.66046099]
 [1.49995478]]
Loss: 0.02786997335540841

Epoch 9
Weights:
 [[0.66109061]
 [1.50121702]]
Loss: 0.027797599021358414

Epoch 10
Weights:
 [[0.66140481]
 [1.50176429]]
Loss: 0.027783207663353696

Epoch 11
Weights:
 [[0.66157814]
 [1.50199332]]
Loss: 0.027780317483969173

Epoch 12
Weights:
 [[0.66168832]
 [1.50208081]]
Loss: 0.027779709295757286

Epoch 13
Weights:
 [[0.66177   ]
 [1.50210544]]
Loss: 0.027779554551219554

Epoch 14
Weights:
 [[0.66183858]
 [1.50210223]